services:
  postgresql:
    image: postgres
    container_name: pgkquizbot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgkquizbot
    ports:
      - "5432:5432"
    volumes:
      - pgdatapgkquizbot:/var/lib/postgresql/data
    networks:
      - backendpgkquizbot

  liquibase-migrations:
    container_name: migrationspgkquizbot
    image: liquibase/liquibase
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/pgkquizbot
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - backendpgkquizbot

volumes:
  pgdatapgkquizbot:

networks:
  backendpgkquizbot:
