CREATE TABLE "users"
(
    "tg_id"       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        TEXT,
    "group_name"       TEXT,
    "cur_question" INTEGER,
    "score"        INTEGER,
    "state"       INTEGER,
    "last_message_id" INTEGER,
    PRIMARY KEY ("tg_id")
);

CREATE TABLE "questions"
(
    "id"       INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "question" TEXT    NOT NULL,
    "answers"  TEXT ARRAY,
    "true_ans" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

